### ISSUE TITLE
Copy not accepting wildcards + file ending anymore when using -r

### ISSUE THREAD

**Issue by kurtextrem** [shelljs/shelljs#376]
So while `ls("src/*.html")` returns an array of html files, `copy("-r", "src/*.html", "dist")` results in an error. It works without -r.
I'm on Windows 7 x64, Node 5.7, using 0.6.

**Comment by ariporad** [comment]
@kurtextrem: Hi! Thanks for the bug report!

This is actually expected behavior, `cp` with the `-r` options means to copy recursively, which only works on directories. If you want to copy all `.html` files in `src/` recursively (ie. even `src/foo/bar/baz.html`), then you're looking for `cp('src/**/*.html', 'dist')`.

The error message is incorrect though, and I'll fix that.

I'm going to close this, but if I've misunderstood, please feel free to reopen!

**Comment by nfischer** [comment]
I'm reopening this, since `-r` *should* be allowed on files. `cp('file.txt', 'dest/')` should do the exactly the same thing as `cp('-r', 'file.txt', 'dest/')`. Just tested this on v0.6 and there seems to be some weird behavior going on.

I'll test again off the master branch and provide a fix if I see the bug there as well. Thanks for reporting this!

**Comment by kurtextrem** [comment]
Thank you for the explanation :)
Glad that my report wasn't that useless.

**Comment by nfischer** [comment]
@kurtextrem As a workaround for now, you can do what @ariporad suggests (no `-r` option).

**Comment by kurtextrem** [comment]
Done :+1: thanks.

**Comment by nfischer** [comment]
Looks like this *was* a bug in `v0.6`, but isn't a bug in the master branch. The best kind of bugs are the ones you unintentionally fix :+1:

I've added some more unit tests for this behavior. This fix will be available in `v0.7`.

@kurtextrem could you please look over the tests and confirm that I'm correctly handling the behavior you describe? Take a look at #378. Thanks!

**Comment by nfischer** [comment]
Looks like I spoke too soon...

I think this is still an issue. Steps to reproduce:

```Javascript
> touch('file.txt');
> cp('file.txt', 'file2.txt'); // this works correctly. `file2.txt` is a regular file
> cp('-r', 'file.txt', 'file3.txt'); // this is wrong. `file3.txt` is actually a directory containing `file1.txt`
```

Looks like this bug is visible [on this line in cash](https://github.com/dthree/cash/blob/master/gulpfile.js#L92).

**Comment by kurtextrem** [comment]
Great, thanks!

**Comment by jimthedev** [comment]
Looking forward to 0.7.0 for this to be released.

**Comment by nfischer** [comment]
@jimthedev Yeah, I'm trying to expedite `v0.7` now to get this bug fix out sooner. I'll start pushing back some things to `v0.8` and work today on the final pieces of `v0.7`.

**Comment by jimthedev** [comment]
@nfischer sounds good. I'm hanging out on 0.5 until then so no rush.

**Comment by nfischer** [comment]
This should be fixed in v0.7, which just got released
